package rardecode

import (
	"encoding/hex"
	"hash"
	"testing"
)

// Test vectors for BLAKE2sp are generated from the reference C implementation.
// See: https://github.com/BLAKE2/BLAKE2/tree/master/testvectors

func TestBLAKE2spEmpty(t *testing.T) {
	// BLAKE2sp hash of empty input
	// Reference: generated by the official BLAKE2 reference implementation
	// blake2sp("") = dd0e891776933f43c7d032b08a917e25741f8aa9a12c12e1cac8801500f2ca4f
	expected := "dd0e891776933f43c7d032b08a917e25741f8aa9a12c12e1cac8801500f2ca4f"
	h := newBLAKE2sp()
	got := hex.EncodeToString(h.Sum(nil))
	if got != expected {
		t.Errorf("BLAKE2sp empty:\ngot  %s\nwant %s", got, expected)
	}
}

func TestBLAKE2spABC(t *testing.T) {
	// BLAKE2sp hash of "abc"
	// Reference: generated by b2sum --blake2sp
	expected := "70f75b58f1fecab821db43c88ad84edde5a52600616cd22517b7bb14d440a7d5"
	h := newBLAKE2sp()
	h.Write([]byte("abc"))
	got := hex.EncodeToString(h.Sum(nil))
	if got != expected {
		t.Errorf("BLAKE2sp 'abc':\ngot  %s\nwant %s", got, expected)
	}
}

func TestBLAKE2spSequential(t *testing.T) {
	// Test with sequential byte input (0x00, 0x01, ..., 0xFF)
	// This exercises multi-block behavior and interleaving
	data := make([]byte, 256)
	for i := range data {
		data[i] = byte(i)
	}
	expected := "5140cfbe0c4ec095dd01713dc470e0ca049e5ba8671984cd28ab510dffee97cd"
	h := newBLAKE2sp()
	h.Write(data)
	got := hex.EncodeToString(h.Sum(nil))
	if got != expected {
		t.Errorf("BLAKE2sp sequential 256:\ngot  %s\nwant %s", got, expected)
	}
}

func TestBLAKE2spInterface(t *testing.T) {
	// Verify it implements hash.Hash
	var h hash.Hash = newBLAKE2sp()
	if h.Size() != 32 {
		t.Errorf("Size() = %d, want 32", h.Size())
	}
	if h.BlockSize() != 512 {
		t.Errorf("BlockSize() = %d, want 512", h.BlockSize())
	}
}

func TestBLAKE2spReset(t *testing.T) {
	h := newBLAKE2sp()
	h.Write([]byte("hello"))
	sum1 := hex.EncodeToString(h.Sum(nil))

	h.Reset()
	h.Write([]byte("hello"))
	sum2 := hex.EncodeToString(h.Sum(nil))

	if sum1 != sum2 {
		t.Errorf("Reset didn't produce same hash:\n%s\n%s", sum1, sum2)
	}
}

func TestBLAKE2spIncrementalWrite(t *testing.T) {
	// Verify byte-at-a-time writing produces the same result as bulk
	data := make([]byte, 1024)
	for i := range data {
		data[i] = byte(i % 251) // prime-sized pattern
	}

	h1 := newBLAKE2sp()
	h1.Write(data)
	bulk := hex.EncodeToString(h1.Sum(nil))

	h2 := newBLAKE2sp()
	for _, b := range data {
		h2.Write([]byte{b})
	}
	incremental := hex.EncodeToString(h2.Sum(nil))

	if bulk != incremental {
		t.Errorf("Incremental vs bulk write differ:\nbulk:        %s\nincremental: %s", bulk, incremental)
	}
}

func TestBLAKE2spSumDoesNotMutate(t *testing.T) {
	// Sum should not modify internal state
	h := newBLAKE2sp()
	h.Write([]byte("test"))

	sum1 := hex.EncodeToString(h.Sum(nil))
	sum2 := hex.EncodeToString(h.Sum(nil))

	if sum1 != sum2 {
		t.Errorf("Sum mutated state:\n%s\n%s", sum1, sum2)
	}

	// Writing more after Sum should change the result
	h.Write([]byte("more"))
	sum3 := hex.EncodeToString(h.Sum(nil))
	if sum3 == sum1 {
		t.Error("Sum after additional Write should differ")
	}
}
