// Code generated by command: go run blake2sp_gen.go -out blake2sp_amd64.s -stubs blake2sp_amd64.go. DO NOT EDIT.

//go:build amd64

package rardecode

// compress8AVX2 runs BLAKE2s compression on 8 blocks in parallel using AVX2.
func compress8AVX2(ctx *byte)
