// Code generated by command: go run filter_rgb_gen.go -out filter_rgb_amd64.s -stubs filter_rgb_amd64.go. DO NOT EDIT.

//go:build amd64

#include "textflag.h"

// func filterRGBAVX2(res []byte, posR int) int
// Requires: AVX, SSE2, SSE4.1
TEXT ·filterRGBAVX2(SB), NOSPLIT, $0-40
	MOVQ    res_base+0(FP), AX
	MOVQ    res_len+8(FP), CX
	MOVQ    posR+24(FP), DX
	MOVQ    CX, CX
	SUBQ    $0x10, CX
	LEAQ    filterRGBMask<>+0(SB), BX
	VMOVDQU (BX), X0

loop:
	CMPQ    DX, CX
	JG      done
	VMOVDQU (AX)(DX*1), X1
	VPSHUFB X0, X1, X2
	VPADDB  X2, X1, X1
	MOVQ    X1, (AX)(DX*1)
	PEXTRD  $0x02, X1, BX
	MOVL    BX, 8(AX)(DX*1)
	PEXTRW  $0x06, X1, BX
	MOVW    BX, 12(AX)(DX*1)
	PEXTRB  $0x0e, X1, BX
	MOVB    BL, 14(AX)(DX*1)
	ADDQ    $0x0f, DX
	JMP     loop

done:
	MOVQ DX, ret+32(FP)
	RET

DATA filterRGBMask<>+0(SB)/1, $0x01
DATA filterRGBMask<>+1(SB)/1, $0x80
DATA filterRGBMask<>+2(SB)/1, $0x01
DATA filterRGBMask<>+3(SB)/1, $0x04
DATA filterRGBMask<>+4(SB)/1, $0x80
DATA filterRGBMask<>+5(SB)/1, $0x04
DATA filterRGBMask<>+6(SB)/1, $0x07
DATA filterRGBMask<>+7(SB)/1, $0x80
DATA filterRGBMask<>+8(SB)/1, $0x07
DATA filterRGBMask<>+9(SB)/1, $0x0a
DATA filterRGBMask<>+10(SB)/1, $0x80
DATA filterRGBMask<>+11(SB)/1, $0x0a
DATA filterRGBMask<>+12(SB)/1, $0x0d
DATA filterRGBMask<>+13(SB)/1, $0x80
DATA filterRGBMask<>+14(SB)/1, $0x0d
DATA filterRGBMask<>+15(SB)/1, $0x80
GLOBL filterRGBMask<>(SB), RODATA, $16
