// Code generated by command: go run filter_arm_gen.go -out filter_arm_amd64.s -stubs filter_arm_amd64.go. DO NOT EDIT.

//go:build amd64

package rardecode

// filterArmAVX2 relocates ARM branch targets using AVX2, returning the number of processed bytes.
func filterArmAVX2(buf []byte, offset int64) int
