// Code generated by command: go run filter_e8_gen.go -out filter_e8_amd64.s -stubs filter_e8_amd64.go. DO NOT EDIT.

//go:build amd64

package rardecode

// filterE8ScanAVX2 scans buf for the first occurrence of 0xe8 or c using AVX2, returning its index.
func filterE8ScanAVX2(buf []byte, c byte) int
