// Code generated by command: go run filter_rgb_gen.go -out filter_rgb_amd64.s -stubs filter_rgb_amd64.go. DO NOT EDIT.

//go:build amd64

package rardecode

// filterRGBAVX2 processes RGB filter post-processing channel additions using AVX2/SSE, returning the next index to process.
func filterRGBAVX2(res []byte, posR int) int
